// 31 Days of Halloween Movie Marathon Dataset
// Generated from October 31 Days of Halloween Movie Marathon - Sheet1.csv

const HALLOWEEN_MOVIES = [
  {
    id: 1,
    dayNumber: 1,
    date: "Oct 1",
    dayOfWeek: "Thu",
    title: "Sleepy Hollow",
    year: "1999",
    runtime: 105,
    status: "First Watch",
    themeKey: "week1",
    themeTitle: "Week 1: Cozy Autumn & Nostalgic Folklore",
    notes: "Tim Burton's mist-drenched, jack-o'-lantern-heavy gothic mystery; autumn kickoff",
    subgenre: "Gothic Horror / Period Mystery",
    director: "Tim Burton",
    backupAlternate: "The Legend of Sleepy Hollow (1949, Disney) or Sleepy Hollow (Series Pilot)",
    icon: "🎃",
    accentColor: "#f97316"
  },
  {
    id: 2,
    dayNumber: 2,
    date: "Oct 2",
    dayOfWeek: "Fri",
    title: "Ghostbusters",
    year: "1984",
    runtime: 105,
    status: "First Watch",
    themeKey: "week1",
    themeTitle: "Week 1: Cozy Autumn & Nostalgic Folklore",
    notes: "Peak 80s practical effects, comedy, and spectral thrills for Friday night",
    subgenre: "Supernatural Comedy / 80s Cult Classic",
    director: "Ivan Reitman",
    backupAlternate: "Ghostbusters II (1989) or Beetlejuice (1988)",
    icon: "👻",
    accentColor: "#38bdf8"
  },
  {
    id: 3,
    dayNumber: 3,
    date: "Oct 3",
    dayOfWeek: "Sat",
    title: "The Village",
    year: "2004",
    runtime: 108,
    status: "Rewatch",
    themeKey: "week1",
    themeTitle: "Week 1: Cozy Autumn & Nostalgic Folklore",
    notes: "Autumn foliage, isolated community folklore, and woodland mystery",
    subgenre: "Woodland Folk Thriller / Mystery",
    director: "M. Night Shyamalan",
    backupAlternate: "The Witch (2015) or Signs (2002)",
    icon: "🌲",
    accentColor: "#eab308"
  },
  {
    id: 4,
    dayNumber: 4,
    date: "Oct 4",
    dayOfWeek: "Sun",
    title: "Wallace & Gromit: The Curse of the Were-Rabbit",
    year: "2005",
    runtime: 85,
    status: "Rewatch",
    themeKey: "week1",
    themeTitle: "Week 1: Cozy Autumn & Nostalgic Folklore",
    notes: "Cozy Sunday stop-motion celebrating harvest vegetables and classic Hammer Horror",
    subgenre: "Claymation / Hammer Horror Parody",
    director: "Nick Park & Steve Box",
    backupAlternate: "Frankenweenie (2012) or Coraline (2009)",
    icon: "🥕",
    accentColor: "#fb923c"
  },
  {
    id: 5,
    dayNumber: 5,
    date: "Oct 5",
    dayOfWeek: "Mon",
    title: "Monster House",
    year: "2006",
    runtime: 91,
    status: "Rewatch",
    themeKey: "week1",
    themeTitle: "Week 1: Cozy Autumn & Nostalgic Folklore",
    notes: "Breezy childhood neighborhood lore and haunted architecture",
    subgenre: "Animated Haunted House / Adventure",
    director: "Gil Kenan",
    backupAlternate: "ParaNorman (2012) or The Burbs (1989)",
    icon: "🏚️",
    accentColor: "#a855f7"
  },
  {
    id: 6,
    dayNumber: 6,
    date: "Oct 6",
    dayOfWeek: "Tue",
    title: "Tremors",
    year: "1990",
    runtime: 96,
    status: "First Watch",
    themeKey: "week1",
    themeTitle: "Week 1: Cozy Autumn & Nostalgic Folklore",
    notes: "Tightly paced creature feature; pure desert monster fun",
    subgenre: "Creature Feature / Desert Horror Comedy",
    director: "Ron Underwood",
    backupAlternate: "Slither (2006) or Eight Legged Freaks (2002)",
    icon: "🪱",
    accentColor: "#d97706"
  },
  {
    id: 7,
    dayNumber: 7,
    date: "Oct 7",
    dayOfWeek: "Wed",
    title: "Happy Death Day",
    year: "2017",
    runtime: 96,
    status: "First Watch",
    themeKey: "week1",
    themeTitle: "Week 1: Cozy Autumn & Nostalgic Folklore",
    notes: "Fast, inventive time-loop slasher",
    subgenre: "Sci-Fi Slasher / Comedy Thriller",
    director: "Christopher Landon",
    backupAlternate: "Freaky (2020) or Totally Killer (2023)",
    icon: "⏰",
    accentColor: "#ec4899"
  },
  {
    id: 8,
    dayNumber: 8,
    date: "Oct 8",
    dayOfWeek: "Thu",
    title: "The Howling",
    year: "1981",
    runtime: 91,
    status: "First Watch",
    themeKey: "week2",
    themeTitle: "Week 2: Practical Blood, 80s Camp & Claws",
    notes: "Joe Dante's landmark 80s werewolf classic with iconic practical transformations",
    subgenre: "Werewolf / Practical FX Horror",
    director: "Joe Dante",
    backupAlternate: "An American Werewolf in London (1981) or Silver Bullet (1985)",
    icon: "🐺",
    accentColor: "#ef4444"
  },
  {
    id: 9,
    dayNumber: 9,
    date: "Oct 9",
    dayOfWeek: "Fri",
    title: "Re-Animator",
    year: "1985",
    runtime: 86,
    status: "First Watch",
    themeKey: "week2",
    themeTitle: "Week 2: Practical Blood, 80s Camp & Claws",
    notes: "Stuart Gordon's unhinged Lovecraftian splatter-comedy; midnight movie energy",
    subgenre: "Splatter Comedy / Lovecraftian Sci-Fi",
    director: "Stuart Gordon",
    backupAlternate: "From Beyond (1986) or Evil Dead II (1987)",
    icon: "🧪",
    accentColor: "#22c55e"
  },
  {
    id: 10,
    dayNumber: 10,
    date: "Oct 10",
    dayOfWeek: "Sat",
    title: "Bram Stoker's Dracula",
    year: "1992",
    runtime: 128,
    status: "First Watch",
    themeKey: "week2",
    themeTitle: "Week 2: Practical Blood, 80s Camp & Claws",
    notes: "Francis Ford Coppola's lavish, operatic gothic spectacle",
    subgenre: "Gothic Vampire Epic / Romance",
    director: "Francis Ford Coppola",
    backupAlternate: "Interview with the Vampire (1994) or Fright Night (1985)",
    icon: "🧛",
    accentColor: "#b91c1c"
  },
  {
    id: 11,
    dayNumber: 11,
    date: "Oct 11",
    dayOfWeek: "Sun",
    title: "Sinners",
    year: "2025",
    runtime: 125,
    status: "First Watch",
    themeKey: "week2",
    themeTitle: "Week 2: Practical Blood, 80s Camp & Claws",
    notes: "Ryan Coogler's period southern gothic supernatural thriller",
    subgenre: "Southern Gothic / Supernatural Thriller",
    director: "Ryan Coogler",
    backupAlternate: "Angel Heart (1987) or Near Dark (1987)",
    icon: "🩸",
    accentColor: "#991b1b"
  },
  {
    id: 12,
    dayNumber: 12,
    date: "Oct 12",
    dayOfWeek: "Mon",
    title: "Children of the Corn",
    year: "1984",
    runtime: 92,
    status: "First Watch",
    themeKey: "week2",
    themeTitle: "Week 2: Practical Blood, 80s Camp & Claws",
    notes: "Agrarian folk horror; harvest rituals and Nebraska backroads",
    subgenre: "Folk Horror / Cult Slasher",
    director: "Fritz Kiersch",
    backupAlternate: "The Wicker Man (1973) or In the Tall Grass (2019)",
    icon: "🌽",
    accentColor: "#ca8a04"
  },
  {
    id: 13,
    dayNumber: 13,
    date: "Oct 13",
    dayOfWeek: "Tue",
    title: "Night of the Living Dead",
    year: "1968",
    runtime: 96,
    status: "Rewatch",
    themeKey: "week2",
    themeTitle: "Week 2: Practical Blood, 80s Camp & Claws",
    notes: "Claustrophobic bedrock of modern zombie cinema",
    subgenre: "Zombie / Black & White Classic",
    director: "George A. Romero",
    backupAlternate: "Dawn of the Dead (1978 or 2004) or Day of the Dead (1985)",
    icon: "🧟",
    accentColor: "#64748b"
  },
  {
    id: 14,
    dayNumber: 14,
    date: "Oct 14",
    dayOfWeek: "Wed",
    title: "The Hills Have Eyes",
    year: "1977",
    runtime: 89,
    status: "First Watch",
    themeKey: "week2",
    themeTitle: "Week 2: Practical Blood, 80s Camp & Claws",
    notes: "Wes Craven's raw, stripped-down desert survival horror",
    subgenre: "Survival Horror / Grindhouse",
    director: "Wes Craven",
    backupAlternate: "The Texas Chain Saw Massacre (1974) or Deliverance (1972)",
    icon: "🏜️",
    accentColor: "#ea580c"
  },
  {
    id: 15,
    dayNumber: 15,
    date: "Oct 15",
    dayOfWeek: "Thu",
    title: "Invasion of the Body Snatchers",
    year: "1978",
    runtime: 115,
    status: "First Watch",
    themeKey: "week3",
    themeTitle: "Week 3: Psychological Paranoia & Suspense",
    notes: "Masterclass in slow-burn paranoia and urban dread",
    subgenre: "Sci-Fi Horror / Paranoia Thriller",
    director: "Philip Kaufman",
    backupAlternate: "The Thing (1982) or The Faculty (1998)",
    icon: "🫘",
    accentColor: "#059669"
  },
  {
    id: 16,
    dayNumber: 16,
    date: "Oct 16",
    dayOfWeek: "Fri",
    title: "Green Room",
    year: "2015",
    runtime: 95,
    status: "Rewatch",
    themeKey: "week3",
    themeTitle: "Week 3: Psychological Paranoia & Suspense",
    notes: "White-knuckle, hyper-intense punk-rock survival siege",
    subgenre: "Siege Thriller / Hardcore Suspense",
    director: "Jeremy Saulnier",
    backupAlternate: "Don't Breathe (2016) or Blue Ruin (2013)",
    icon: "🎸",
    accentColor: "#10b981"
  },
  {
    id: 17,
    dayNumber: 17,
    date: "Oct 17",
    dayOfWeek: "Sat",
    title: "Scream",
    year: "1996",
    runtime: 111,
    status: "Rewatch",
    themeKey: "week3",
    themeTitle: "Week 3: Psychological Paranoia & Suspense",
    notes: "Wes Craven's sharp meta-slasher royalty",
    subgenre: "Meta Slasher / Whodunit",
    director: "Wes Craven",
    backupAlternate: "Scream 2 (1997) or I Know What You Did Last Summer (1997)",
    icon: "🔪",
    accentColor: "#f43f5e"
  },
  {
    id: 18,
    dayNumber: 18,
    date: "Oct 18",
    dayOfWeek: "Sun",
    title: "Rosemary's Baby",
    year: "1968",
    runtime: 137,
    status: "First Watch",
    themeKey: "week3",
    themeTitle: "Week 3: Psychological Paranoia & Suspense",
    notes: "Slow-boiling psychological dread, gaslighting, and domestic witchcraft",
    subgenre: "Psychological Horror / Occult Paranoia",
    director: "Roman Polanski",
    backupAlternate: "The Stepford Wives (1975) or Hereditary (2018)",
    icon: "🍼",
    accentColor: "#d946ef"
  },
  {
    id: 19,
    dayNumber: 19,
    date: "Oct 19",
    dayOfWeek: "Mon",
    title: "Eyes Without a Face",
    year: "1960",
    runtime: 90,
    status: "First Watch",
    themeKey: "week3",
    themeTitle: "Week 3: Psychological Paranoia & Suspense",
    notes: "Poetic, haunting French gothic horror (inspired Michael Myers' mask)",
    subgenre: "French Gothic / Melodrama of Terror",
    director: "Georges Franju",
    backupAlternate: "Diabolique (1955) or The Skin I Live In (2011)",
    icon: "🎭",
    accentColor: "#94a3b8"
  },
  {
    id: 20,
    dayNumber: 20,
    date: "Oct 20",
    dayOfWeek: "Tue",
    title: "Donnie Darko",
    year: "2001",
    runtime: 113,
    status: "Rewatch",
    themeKey: "week3",
    themeTitle: "Week 3: Psychological Paranoia & Suspense",
    notes: "Late-October suburban angst, surreal countdowns, and autumn melancholy",
    subgenre: "Cult Sci-Fi / Psychological Mystery",
    director: "Richard Kelly",
    backupAlternate: "The Butterfly Effect (2004) or Coherence (2013)",
    icon: "🐰",
    accentColor: "#6366f1"
  },
  {
    id: 21,
    dayNumber: 21,
    date: "Oct 21",
    dayOfWeek: "Wed",
    title: "Scary Stories to Tell in the Dark",
    year: "2019",
    runtime: 108,
    status: "Rewatch",
    themeKey: "week3",
    themeTitle: "Week 3: Psychological Paranoia & Suspense",
    notes: "Halloween 1968 setting, haunted folklore, and creature nightmares",
    subgenre: "Folklore Horror / Creature Anthology",
    director: "André Øvredal",
    backupAlternate: "Goosebumps (2015) or Fear Street: 1994 (2021)",
    icon: "📖",
    accentColor: "#84cc16"
  },
  {
    id: 22,
    dayNumber: 22,
    date: "Oct 22",
    dayOfWeek: "Thu",
    title: "Poltergeist",
    year: "1982",
    runtime: 114,
    status: "First Watch",
    themeKey: "week4",
    themeTitle: "Week 4: Haunted Ground & Occult Dread",
    notes: "Definitive 80s suburban haunted house landmark",
    subgenre: "Haunted House / Supernatural Horror",
    director: "Tobe Hooper (with Steven Spielberg)",
    backupAlternate: "The Amityville Horror (1979) or The Changeling (1980)",
    icon: "📺",
    accentColor: "#38bdf8"
  },
  {
    id: 23,
    dayNumber: 23,
    date: "Oct 23",
    dayOfWeek: "Fri",
    title: "The Conjuring",
    year: "2013",
    runtime: 112,
    status: "Rewatch",
    themeKey: "week4",
    themeTitle: "Week 4: Haunted Ground & Occult Dread",
    notes: "Modern haunted-house engineering and relentless tension",
    subgenre: "Supernatural / Demonology",
    director: "James Wan",
    backupAlternate: "Insidious (2010) or Sinister (2012)",
    icon: "🕯️",
    accentColor: "#f59e0b"
  },
  {
    id: 24,
    dayNumber: 24,
    date: "Oct 24",
    dayOfWeek: "Sat",
    title: "The Wailing",
    year: "2016",
    runtime: 156,
    status: "First Watch",
    themeKey: "week4",
    themeTitle: "Week 4: Haunted Ground & Occult Dread",
    notes: "Immersive Korean occult masterpiece of infection, doubt, and malice",
    subgenre: "Korean Occult / Police Procedural Horror",
    director: "Na Hong-jin",
    backupAlternate: "The Medium (2021) or Cure (1997)",
    icon: "🌧️",
    accentColor: "#8b5cf6"
  },
  {
    id: 25,
    dayNumber: 25,
    date: "Oct 25",
    dayOfWeek: "Sun",
    title: "It's the Great Pumpkin, Charlie Brown + Over the Garden Wall",
    year: "1966 / 2014",
    runtime: 135,
    status: "Rewatch",
    themeKey: "week4",
    themeTitle: "Week 4: Haunted Ground & Occult Dread",
    notes: "Official Pumpkin Carving Night: double-feature ritual with autumn leaves and harvest spirit",
    subgenre: "Autumn Harvest Folklore / Animation Double-Feature",
    director: "Bill Melendez / Patrick McHale",
    backupAlternate: "Coraline (2009) or The Nightmare Before Christmas (1993)",
    icon: "🍂",
    accentColor: "#f97316"
  },
  {
    id: 26,
    dayNumber: 26,
    date: "Oct 26",
    dayOfWeek: "Mon",
    title: "Train to Busan",
    year: "2016",
    runtime: 118,
    status: "Rewatch",
    themeKey: "week4",
    themeTitle: "Week 4: Haunted Ground & Occult Dread",
    notes: "Kinetic, high-velocity zombie survival thriller",
    subgenre: "High-Octane Zombie Thriller",
    director: "Yeon Sang-ho",
    backupAlternate: "#Alive (2020) or 28 Days Later (2002)",
    icon: "🚆",
    accentColor: "#ef4444"
  },
  {
    id: 27,
    dayNumber: 27,
    date: "Oct 27",
    dayOfWeek: "Tue",
    title: "Colony",
    year: "2026",
    runtime: 100,
    status: "First Watch",
    themeKey: "week4",
    themeTitle: "Week 4: Haunted Ground & Occult Dread",
    notes: "Tense quarantine outbreak siege keeping adrenaline high",
    subgenre: "Outbreak / Quarantine Siege",
    director: "Indie Feature",
    backupAlternate: "The Crazies (2010) or [REC] (2007)",
    icon: "☣️",
    accentColor: "#e11d48"
  },
  {
    id: 28,
    dayNumber: 28,
    date: "Oct 28",
    dayOfWeek: "Wed",
    title: "Hocus Pocus",
    year: "1993",
    runtime: 96,
    status: "Rewatch",
    themeKey: "finale",
    themeTitle: "The Finale: All Hallows' Eve",
    notes: "Nostalgic Salem comfort food & witchy celebration leading into Halloween weekend",
    subgenre: "Salem Witchcraft / Family Fantasy",
    director: "Kenny Ortega",
    backupAlternate: "The Witches (1990) or Practical Magic (1998)",
    icon: "🧙‍♀️",
    accentColor: "#a855f7"
  },
  {
    id: 29,
    dayNumber: 29,
    date: "Oct 29",
    dayOfWeek: "Thu",
    title: "Exhuma",
    year: "2024",
    runtime: 134,
    status: "First Watch",
    themeKey: "finale",
    themeTitle: "The Finale: All Hallows' Eve",
    notes: "Ancestral curses, shamanic rituals, and unearthed graves",
    subgenre: "K-Occult / Shamanic Mystery",
    director: "Jang Jae-hyun",
    backupAlternate: "The Priest (2015) or Svaha: The Sixth Finger (2019)",
    icon: "⚰️",
    accentColor: "#78716c"
  },
  {
    id: 30,
    dayNumber: 30,
    date: "Oct 30",
    dayOfWeek: "Fri",
    title: "Trick 'r Treat",
    year: "2007",
    runtime: 82,
    status: "First Watch",
    themeKey: "finale",
    themeTitle: "The Finale: All Hallows' Eve",
    notes: "Devil's Night: Anthology honoring Halloween lore, traditions, and Sam",
    subgenre: "Halloween Anthology / Dark Comedy",
    director: "Michael Dougherty",
    backupAlternate: "Tales of Halloween (2015) or Creepshow (1982)",
    icon: "🍭",
    accentColor: "#f97316"
  },
  {
    id: 31,
    dayNumber: 31,
    date: "Oct 31",
    dayOfWeek: "Sat",
    title: "Halloween",
    year: "1978",
    runtime: 91,
    status: "Rewatch",
    themeKey: "finale",
    themeTitle: "The Finale: All Hallows' Eve",
    notes: "All Hallows' Eve: The undisputed holiday classic, synth score, and the Shape stalking Haddonfield",
    subgenre: "Foundational Slasher / Masterpiece",
    director: "John Carpenter",
    backupAlternate: "Halloween II (1981) or Halloween (2018)",
    icon: "🎃",
    accentColor: "#ea580c"
  }
];

const THEMES = [
  {
    key: "all",
    label: "All 31 Days",
    dateRange: "Oct 1 – Oct 31",
    icon: "🦇"
  },
  {
    key: "week1",
    label: "Week 1: Cozy Autumn & Folklore",
    dateRange: "Oct 1 – Oct 7",
    description: "Mist-drenched kickoff, cozy stop-motion, harvest veggies & creature fun",
    color: "#f97316",
    icon: "🍁"
  },
  {
    key: "week2",
    label: "Week 2: Practical Blood, 80s Camp & Claws",
    dateRange: "Oct 8 – Oct 14",
    description: "Gory practical transformations, Lovecraftian splatter & southern dread",
    color: "#ef4444",
    icon: "🩸"
  },
  {
    key: "week3",
    label: "Week 3: Psychological Paranoia & Suspense",
    dateRange: "Oct 15 – Oct 21",
    description: "Slow-burn urban dread, siege tension, meta-slashers & suburban angst",
    color: "#8b5cf6",
    icon: "👁️"
  },
  {
    key: "week4",
    label: "Week 4: Haunted Ground & Occult Dread",
    dateRange: "Oct 22 – Oct 27",
    description: "Suburban hauntings, demonology, Korean folk terror & pumpkin ritual",
    color: "#06b6d4",
    icon: "🕯️"
  },
  {
    key: "finale",
    label: "The Finale: All Hallows' Eve",
    dateRange: "Oct 28 – Oct 31",
    description: "Salem comfort, ancestral curses, Sam's rules & Carpenter's Shape",
    color: "#fb923c",
    icon: "🎃"
  }
];
