// 31 Days of Halloween Movie Marathon Dataset
// Generated from October 31 Days of Halloween Movie Marathon - Sheet1.csv
// Enriched with Letterboxd-style synopses, Scare Ratings (1-5), and standardized Genre categories.

const HALLOWEEN_MOVIES = [
  {
    id: 1,
    dayNumber: 1,
    date: "Oct 1",
    dayOfWeek: "Thu",
    title: "Sleepy Hollow",
    year: "1999",
    runtime: 105,
    status: "First Watch",
    themeKey: "week1",
    themeTitle: "Week 1: Cozy Autumn & Nostalgic Folklore",
    notes: "Tim Burton's mist-drenched, jack-o'-lantern-heavy gothic mystery; autumn kickoff",
    synopsis: "New York constable Ichabod Crane is dispatched to the secluded hamlet of Sleepy Hollow to investigate a string of grisly decapitations attributed to a legendary phantom: the Headless Horseman.",
    subgenre: "Gothic Horror / Period Mystery",
    genreCategory: "Ghost & Haunted",
    scareRating: 3,
    scareLabel: "Moderate Chills",
    scareVibe: "Atmospheric gothic mist, severed heads, dark fairy tale gore",
    director: "Tim Burton",
    backupAlternate: "The Legend of Sleepy Hollow (1949, Disney) or Sleepy Hollow (Series Pilot)",
    icon: "🎃",
    accentColor: "#f97316"
  },
  {
    id: 2,
    dayNumber: 2,
    date: "Oct 2",
    dayOfWeek: "Fri",
    title: "Ghostbusters",
    year: "1984",
    runtime: 105,
    status: "First Watch",
    themeKey: "week1",
    themeTitle: "Week 1: Cozy Autumn & Nostalgic Folklore",
    notes: "Peak 80s practical effects, comedy, and spectral thrills for Friday night",
    synopsis: "Three eccentric parapsychology professors set up a unique ghost-removal service in New York City, inadvertently stumbling into a battle against an ancient Sumerian god bent on world destruction.",
    subgenre: "Supernatural Comedy / 80s Cult Classic",
    genreCategory: "Ghost & Haunted",
    scareRating: 2,
    scareLabel: "Mild Thrills",
    scareVibe: "Goofy green slime, library spook, marshmallow chaos",
    director: "Ivan Reitman",
    backupAlternate: "Ghostbusters II (1989) or Beetlejuice (1988)",
    icon: "👻",
    accentColor: "#38bdf8"
  },
  {
    id: 3,
    dayNumber: 3,
    date: "Oct 3",
    dayOfWeek: "Sat",
    title: "The Village",
    year: "2004",
    runtime: 108,
    status: "Rewatch",
    themeKey: "week1",
    themeTitle: "Week 1: Cozy Autumn & Nostalgic Folklore",
    notes: "Autumn foliage, isolated community folklore, and woodland mystery",
    synopsis: "Residents of an isolated 19th-century Pennsylvania community live in uneasy truce with monstrous, red-cloaked creatures lurking in the surrounding woods—until a blind woman ventures beyond the perimeter.",
    subgenre: "Woodland Folk Thriller / Mystery",
    genreCategory: "Occult & Folk",
    scareRating: 3,
    scareLabel: "Moderate Chills",
    scareVibe: "Eerie silence, woodland suspense, sensory tension",
    director: "M. Night Shyamalan",
    backupAlternate: "The Witch (2015) or Signs (2002)",
    icon: "🌲",
    accentColor: "#eab308"
  },
  {
    id: 4,
    dayNumber: 4,
    date: "Oct 4",
    dayOfWeek: "Sun",
    title: "Wallace & Gromit: The Curse of the Were-Rabbit",
    year: "2005",
    runtime: 85,
    status: "Rewatch",
    themeKey: "week1",
    themeTitle: "Week 1: Cozy Autumn & Nostalgic Folklore",
    notes: "Cozy Sunday stop-motion celebrating harvest vegetables and classic Hammer Horror",
    synopsis: "Eccentric inventor Wallace and his sensible canine companion Gromit must unravel the mystery of a colossal, ravenous beast wreaking havoc on the town's prize vegetables before the annual Giant Vegetable Competition.",
    subgenre: "Claymation / Hammer Horror Parody",
    genreCategory: "Family & Dark Fantasy",
    scareRating: 1,
    scareLabel: "Cozy Spooks",
    scareVibe: "Pure cozy harvest comfort, gentle monster parody, zero nightmare fuel",
    director: "Nick Park & Steve Box",
    backupAlternate: "Frankenweenie (2012) or Coraline (2009)",
    icon: "🥕",
    accentColor: "#fb923c"
  },
  {
    id: 5,
    dayNumber: 5,
    date: "Oct 5",
    dayOfWeek: "Mon",
    title: "Monster House",
    year: "2006",
    runtime: 91,
    status: "Rewatch",
    themeKey: "week1",
    themeTitle: "Week 1: Cozy Autumn & Nostalgic Folklore",
    notes: "Breezy childhood neighborhood lore and haunted architecture",
    synopsis: "Three suburban teenagers discover that the decrepit residence across the street is not merely haunted, but a living, malevolent organism that swallows anything crossing its lawn on Halloween week.",
    subgenre: "Animated Haunted House / Adventure",
    genreCategory: "Ghost & Haunted",
    scareRating: 2,
    scareLabel: "Mild Thrills",
    scareVibe: "Creepy architectural monster, Amblin-esque adventure tension",
    director: "Gil Kenan",
    backupAlternate: "ParaNorman (2012) or The Burbs (1989)",
    icon: "🏚️",
    accentColor: "#a855f7"
  },
  {
    id: 6,
    dayNumber: 6,
    date: "Oct 6",
    dayOfWeek: "Tue",
    title: "Tremors",
    year: "1990",
    runtime: 96,
    status: "First Watch",
    themeKey: "week1",
    themeTitle: "Week 1: Cozy Autumn & Nostalgic Folklore",
    notes: "Tightly paced creature feature; pure desert monster fun",
    synopsis: "Handymen Val and Earl find themselves stranded in the isolated desert town of Perfection, Nevada, under siege by subterranean, ravenous carnivorous worms that hunt purely by acoustic vibration.",
    subgenre: "Creature Feature / Desert Horror Comedy",
    genreCategory: "Creature",
    scareRating: 2,
    scareLabel: "Mild Thrills",
    scareVibe: "Fast monster fun, desert explosions, creature mayhem",
    director: "Ron Underwood",
    backupAlternate: "Slither (2006) or Eight Legged Freaks (2002)",
    icon: "🪱",
    accentColor: "#d97706"
  },
  {
    id: 7,
    dayNumber: 7,
    date: "Oct 7",
    dayOfWeek: "Wed",
    title: "Happy Death Day",
    year: "2017",
    runtime: 96,
    status: "First Watch",
    themeKey: "week1",
    themeTitle: "Week 1: Cozy Autumn & Nostalgic Folklore",
    notes: "Fast, inventive time-loop slasher",
    synopsis: "A self-absorbed college student is murdered by a baby-masked killer on her birthday, only to wake up completely unharmed in the same morning—doomed to repeat the day until she uncovers who wants her dead.",
    subgenre: "Sci-Fi Slasher / Comedy Thriller",
    genreCategory: "Slasher",
    scareRating: 3,
    scareLabel: "Moderate Chills",
    scareVibe: "Inventive time-loop kills, dark humor, slasher stalking",
    director: "Christopher Landon",
    backupAlternate: "Freaky (2020) or Totally Killer (2023)",
    icon: "⏰",
    accentColor: "#ec4899"
  },
  {
    id: 8,
    dayNumber: 8,
    date: "Oct 8",
    dayOfWeek: "Thu",
    title: "The Howling",
    year: "1981",
    runtime: 91,
    status: "First Watch",
    themeKey: "week2",
    themeTitle: "Week 2: Practical Blood, 80s Camp & Claws",
    notes: "Joe Dante's landmark 80s werewolf classic with iconic practical transformations",
    synopsis: "Following a near-fatal brush with a serial killer, a Los Angeles news anchor retreats to an isolated coastal commune to recuperate, unaware the eccentric residents are shape-shifting werewolves.",
    subgenre: "Werewolf / Practical FX Horror",
    genreCategory: "Creature",
    scareRating: 3,
    scareLabel: "Moderate Chills",
    scareVibe: "Iconic body-stretching practical effects, lupine savagery, 80s satire",
    director: "Joe Dante",
    backupAlternate: "An American Werewolf in London (1981) or Silver Bullet (1985)",
    icon: "🐺",
    accentColor: "#ef4444"
  },
  {
    id: 9,
    dayNumber: 9,
    date: "Oct 9",
    dayOfWeek: "Fri",
    title: "Re-Animator",
    year: "1985",
    runtime: 86,
    status: "First Watch",
    themeKey: "week2",
    themeTitle: "Week 2: Practical Blood, 80s Camp & Claws",
    notes: "Stuart Gordon's unhinged Lovecraftian splatter-comedy; midnight movie energy",
    synopsis: "A brilliant, demented medical student invents a luminous green reagent that reanimates deceased brain tissue, plunging a prestigious university hospital into an uncontrolled bloodbath of runaway corpses.",
    subgenre: "Splatter Comedy / Lovecraftian Sci-Fi",
    genreCategory: "Zombie & Outbreak",
    scareRating: 4,
    scareLabel: "High Terror / Gore",
    scareVibe: "Unhinged practical splatter, mad scientist gore, midnight chaos",
    director: "Stuart Gordon",
    backupAlternate: "From Beyond (1986) or Evil Dead II (1987)",
    icon: "🧪",
    accentColor: "#22c55e"
  },
  {
    id: 10,
    dayNumber: 10,
    date: "Oct 10",
    dayOfWeek: "Sat",
    title: "Bram Stoker's Dracula",
    year: "1992",
    runtime: 128,
    status: "First Watch",
    themeKey: "week2",
    themeTitle: "Week 2: Practical Blood, 80s Camp & Claws",
    notes: "Francis Ford Coppola's lavish, operatic gothic spectacle",
    synopsis: "Centuries after cursing God over the death of his bride, Count Dracula travels from Transylvania to Victorian London seduced by a woman he believes is the reincarnation of his true love.",
    subgenre: "Gothic Vampire Epic / Romance",
    genreCategory: "Dark Fantasy",
    scareRating: 3,
    scareLabel: "Moderate Chills",
    scareVibe: "Lavish blood-red aesthetics, in-camera shadow tricks, sensual dread",
    director: "Francis Ford Coppola",
    backupAlternate: "Interview with the Vampire (1994) or Fright Night (1985)",
    icon: "🧛",
    accentColor: "#b91c1c"
  },
  {
    id: 11,
    dayNumber: 11,
    date: "Oct 11",
    dayOfWeek: "Sun",
    title: "Sinners",
    year: "2025",
    runtime: 125,
    status: "First Watch",
    themeKey: "week2",
    themeTitle: "Week 2: Practical Blood, 80s Camp & Claws",
    notes: "Ryan Coogler's period southern gothic supernatural thriller",
    synopsis: "In the Jim Crow-era American South, twin brothers return home hoping to leave their troubled pasts behind, only to discover an ancient and unspeakable supernatural terror lying in wait.",
    subgenre: "Southern Gothic / Supernatural Thriller",
    genreCategory: "Occult & Folk",
    scareRating: 4,
    scareLabel: "High Terror",
    scareVibe: "Southern gothic dread, supernatural tension, high emotional stakes",
    director: "Ryan Coogler",
    backupAlternate: "Angel Heart (1987) or Near Dark (1987)",
    icon: "🩸",
    accentColor: "#991b1b"
  },
  {
    id: 12,
    dayNumber: 12,
    date: "Oct 12",
    dayOfWeek: "Mon",
    title: "Children of the Corn",
    year: "1984",
    runtime: 92,
    status: "First Watch",
    themeKey: "week2",
    themeTitle: "Week 2: Practical Blood, 80s Camp & Claws",
    notes: "Agrarian folk horror; harvest rituals and Nebraska backroads",
    synopsis: "A traveling physician and his girlfriend arrive in the remote, desolate town of Gatlin, Nebraska, stumbling upon a fanatical child cult that sacrifices anyone over the age of nineteen to a deity in the cornfields.",
    subgenre: "Folk Horror / Cult Slasher",
    genreCategory: "Occult & Folk",
    scareRating: 3,
    scareLabel: "Moderate Chills",
    scareVibe: "Whispering corn stalks, scythe-wielding youths, eerie religious cult",
    director: "Fritz Kiersch",
    backupAlternate: "The Wicker Man (1973) or In the Tall Grass (2019)",
    icon: "🌽",
    accentColor: "#ca8a04"
  },
  {
    id: 13,
    dayNumber: 13,
    date: "Oct 13",
    dayOfWeek: "Tue",
    title: "Night of the Living Dead",
    year: "1968",
    runtime: 96,
    status: "Rewatch",
    themeKey: "week2",
    themeTitle: "Week 2: Practical Blood, 80s Camp & Claws",
    notes: "Claustrophobic bedrock of modern zombie cinema",
    synopsis: "Strangers seek refuge in an isolated Pennsylvania farmhouse as dead bodies across the nation spontaneously reanimate with an unquenchable hunger for living human flesh.",
    subgenre: "Zombie / Black & White Classic",
    genreCategory: "Zombie & Outbreak",
    scareRating: 4,
    scareLabel: "High Terror",
    scareVibe: "Claustrophobic paranoia, relentless barricade siege, bleak historical dread",
    director: "George A. Romero",
    backupAlternate: "Dawn of the Dead (1978 or 2004) or Day of the Dead (1985)",
    icon: "🧟",
    accentColor: "#64748b"
  },
  {
    id: 14,
    dayNumber: 14,
    date: "Oct 14",
    dayOfWeek: "Wed",
    title: "The Hills Have Eyes",
    year: "1977",
    runtime: 89,
    status: "First Watch",
    themeKey: "week2",
    themeTitle: "Week 2: Practical Blood, 80s Camp & Claws",
    notes: "Wes Craven's raw, stripped-down desert survival horror",
    synopsis: "Stranded on an off-limits testing ground in the unforgiving Nevada desert, an ordinary suburban vacationing family is stalked and butchered by a family of inbred, cannibalistic savages.",
    subgenre: "Survival Horror / Grindhouse",
    genreCategory: "Slasher",
    scareRating: 4,
    scareLabel: "High Terror",
    scareVibe: "Raw 70s grindhouse brutality, sun-drenched desert dread, survival savagery",
    director: "Wes Craven",
    backupAlternate: "The Texas Chain Saw Massacre (1974) or Deliverance (1972)",
    icon: "🏜️",
    accentColor: "#ea580c"
  },
  {
    id: 15,
    dayNumber: 15,
    date: "Oct 15",
    dayOfWeek: "Thu",
    title: "Invasion of the Body Snatchers",
    year: "1978",
    runtime: 115,
    status: "First Watch",
    themeKey: "week3",
    themeTitle: "Week 3: Psychological Paranoia & Suspense",
    notes: "Masterclass in slow-burn paranoia and urban dread",
    synopsis: "A San Francisco health inspector begins to notice subtle psychological shifts in his acquaintances, uncovering a terrifying extraterrestrial plot to replace humanity with unfeeling pod clones.",
    subgenre: "Sci-Fi Horror / Paranoia Thriller",
    genreCategory: "Psychological",
    scareRating: 4,
    scareLabel: "High Terror",
    scareVibe: "Suffocating urban paranoia, that iconic screaming pointing scene, total helplessness",
    director: "Philip Kaufman",
    backupAlternate: "The Thing (1982) or The Faculty (1998)",
    icon: "🫘",
    accentColor: "#059669"
  },
  {
    id: 16,
    dayNumber: 16,
    date: "Oct 16",
    dayOfWeek: "Fri",
    title: "Evil Dead II",
    year: "1987",
    runtime: 84,
    status: "First Watch",
    themeKey: "week3",
    themeTitle: "Week 3: Psychological Paranoia & Suspense",
    notes: "Sam Raimi's masterclass in slapstick gore, frantic camera work, chainsaw arms, and peak Deadite camp to lighten the week",
    synopsis: "Ash Williams retreats to a secluded woodland cabin with his girlfriend, only to accidentally unleash flesh-possessing demons from the ancient Book of the Dead, forcing him into a blood-soaked, slapstick war for survival against his own possessed hand and airborne Deadites.",
    subgenre: "Splatter Comedy / Possessed Cabin Horror",
    genreCategory: "Zombie & Outbreak",
    scareRating: 3,
    scareLabel: "Moderate Chills / Splatter Laughs",
    scareVibe: "Frantic point-of-view rushing cameras, laughing mounted deer heads, severed hands, chainsaw glory",
    director: "Sam Raimi",
    backupAlternate: "Army of Darkness (1992) or Drag Me to Hell (2009)",
    icon: "🪚",
    accentColor: "#ef4444"
  },
  {
    id: 17,
    dayNumber: 17,
    date: "Oct 17",
    dayOfWeek: "Sat",
    title: "Scream",
    year: "1996",
    runtime: 111,
    status: "Rewatch",
    themeKey: "week3",
    themeTitle: "Week 3: Psychological Paranoia & Suspense",
    notes: "Wes Craven's sharp meta-slasher royalty",
    synopsis: "A masked serial killer obsessed with scary movie trivia terrorizes the sleepy California town of Woodsboro, taunting high schooler Sidney Prescott and her cinephile classmates before striking.",
    subgenre: "Meta Slasher / Whodunit",
    genreCategory: "Slasher",
    scareRating: 3,
    scareLabel: "Moderate Chills",
    scareVibe: "Iconic telephone opening, witty meta-humor, sharp slasher jumpscares",
    director: "Wes Craven",
    backupAlternate: "Scream 2 (1997) or I Know What You Did Last Summer (1997)",
    icon: "🔪",
    accentColor: "#f43f5e"
  },
  {
    id: 18,
    dayNumber: 18,
    date: "Oct 18",
    dayOfWeek: "Sun",
    title: "Rosemary's Baby",
    year: "1968",
    runtime: 137,
    status: "First Watch",
    themeKey: "week3",
    themeTitle: "Week 3: Psychological Paranoia & Suspense",
    notes: "Slow-boiling psychological dread, gaslighting, and domestic witchcraft",
    synopsis: "A young newlywed becomes mysteriously pregnant inside an ominous historic Manhattan apartment, gradually coming to suspect her overbearing elderly neighbors have sinister occult plans for her unborn baby.",
    subgenre: "Psychological Horror / Occult Paranoia",
    genreCategory: "Occult & Folk",
    scareRating: 4,
    scareLabel: "High Terror",
    scareVibe: "Slow-boil domestic dread, psychological gaslighting, satanic coven paranoia",
    director: "Roman Polanski",
    backupAlternate: "The Stepford Wives (1975) or Hereditary (2018)",
    icon: "🍼",
    accentColor: "#d946ef"
  },
  {
    id: 19,
    dayNumber: 19,
    date: "Oct 19",
    dayOfWeek: "Mon",
    title: "Eyes Without a Face",
    year: "1960",
    runtime: 90,
    status: "First Watch",
    themeKey: "week3",
    themeTitle: "Week 3: Psychological Paranoia & Suspense",
    notes: "Poetic, haunting French gothic horror (inspired Michael Myers' mask)",
    synopsis: "A guilt-ridden plastic surgeon kidnaps young women to surgically harvest their facial tissue and graft it onto his disfigured daughter, who wanders a secluded mansion trapped behind a lifeless porcelain mask.",
    subgenre: "French Gothic / Melodrama of Terror",
    genreCategory: "Psychological",
    scareRating: 3,
    scareLabel: "Moderate Chills",
    scareVibe: "Haunting poetic melancholy, shocking clinical facial surgery, eerie mask",
    director: "Georges Franju",
    backupAlternate: "Diabolique (1955) or The Skin I Live In (2011)",
    icon: "🎭",
    accentColor: "#94a3b8"
  },
  {
    id: 20,
    dayNumber: 20,
    date: "Oct 20",
    dayOfWeek: "Tue",
    title: "Donnie Darko",
    year: "2001",
    runtime: 113,
    status: "Rewatch",
    themeKey: "week3",
    themeTitle: "Week 3: Psychological Paranoia & Suspense",
    notes: "Late-October suburban angst, surreal countdowns, and autumn melancholy",
    synopsis: "After sleepwalking out of his bedroom moments before a falling jet engine crashes into it, a troubled teenager is plagued by visions of a six-foot demonic rabbit who commands him to commit bizarre crimes.",
    subgenre: "Cult Sci-Fi / Psychological Mystery",
    genreCategory: "Psychological",
    scareRating: 2,
    scareLabel: "Mild Thrills",
    scareVibe: "Spooky suburban countdown, surreal melancholy, haunting giant rabbit",
    director: "Richard Kelly",
    backupAlternate: "The Butterfly Effect (2004) or Coherence (2013)",
    icon: "🐰",
    accentColor: "#6366f1"
  },
  {
    id: 21,
    dayNumber: 21,
    date: "Oct 21",
    dayOfWeek: "Wed",
    title: "Scary Stories to Tell in the Dark",
    year: "2019",
    runtime: 108,
    status: "Rewatch",
    themeKey: "week3",
    themeTitle: "Week 3: Psychological Paranoia & Suspense",
    notes: "Halloween 1968 setting, haunted folklore, and creature nightmares",
    synopsis: "On Halloween night in 1968, a band of outcast teenagers venture into a notorious local haunted house and uncover a handwritten book of horrors that magically writes terrifying new tales targeting each of them.",
    subgenre: "Folklore Horror / Creature Anthology",
    genreCategory: "Occult & Folk",
    scareRating: 3,
    scareLabel: "Moderate Chills",
    scareVibe: "Grotesque creature designs (Pale Lady, Jangly Man), folklore body horror",
    director: "André Øvredal",
    backupAlternate: "Goosebumps (2015) or Fear Street: 1994 (2021)",
    icon: "📖",
    accentColor: "#84cc16"
  },
  {
    id: 22,
    dayNumber: 22,
    date: "Oct 22",
    dayOfWeek: "Thu",
    title: "Poltergeist",
    year: "1982",
    runtime: 114,
    status: "First Watch",
    themeKey: "week4",
    themeTitle: "Week 4: Haunted Ground & Occult Dread",
    notes: "Definitive 80s suburban haunted house landmark",
    synopsis: "A California suburban family discovers demonic spirits have taken residence in their tract home, communicating through the television set before abducting their youngest daughter into another dimension.",
    subgenre: "Haunted House / Supernatural Horror",
    genreCategory: "Ghost & Haunted",
    scareRating: 3,
    scareLabel: "Moderate Chills",
    scareVibe: "Tree abduction, sinister clown doll, bathroom face-peel nightmare",
    director: "Tobe Hooper (with Steven Spielberg)",
    backupAlternate: "The Amityville Horror (1979) or The Changeling (1980)",
    icon: "📺",
    accentColor: "#38bdf8"
  },
  {
    id: 23,
    dayNumber: 23,
    date: "Oct 23",
    dayOfWeek: "Fri",
    title: "The Conjuring",
    year: "2013",
    runtime: 112,
    status: "Rewatch",
    themeKey: "week4",
    themeTitle: "Week 4: Haunted Ground & Occult Dread",
    notes: "Modern haunted-house engineering and relentless tension",
    synopsis: "Demonologists Ed and Lorraine Warren are called to a secluded Rhode Island farmhouse to investigate a terrifying, malevolent supernatural presence terrorizing a family of seven.",
    subgenre: "Supernatural / Demonology",
    genreCategory: "Ghost & Haunted",
    scareRating: 4,
    scareLabel: "High Terror",
    scareVibe: "Clap-clap game in the dark, wardrobe jumpscares, demonic possession",
    director: "James Wan",
    backupAlternate: "Insidious (2010) or Sinister (2012)",
    icon: "🕯️",
    accentColor: "#f59e0b"
  },
  {
    id: 24,
    dayNumber: 24,
    date: "Oct 24",
    dayOfWeek: "Sat",
    title: "The Wailing",
    year: "2016",
    runtime: 156,
    status: "First Watch",
    themeKey: "week4",
    themeTitle: "Week 4: Haunted Ground & Occult Dread",
    notes: "Immersive Korean occult masterpiece of infection, doubt, and malice",
    synopsis: "In a remote mountain village plagued by a bizarre rash of hysterical murders and fungal sickness, an inept police officer scrambles to save his afflicted daughter as ancient evil closes in.",
    subgenre: "Korean Occult / Police Procedural Horror",
    genreCategory: "Occult & Folk",
    scareRating: 5,
    scareLabel: "Extreme Intensity",
    scareVibe: "Deep existential dread, shamanic exorcism rituals, unrelenting rain and malice",
    director: "Na Hong-jin",
    backupAlternate: "The Medium (2021) or Cure (1997)",
    icon: "🌧️",
    accentColor: "#8b5cf6"
  },
  {
    id: 25,
    dayNumber: 25,
    date: "Oct 25",
    dayOfWeek: "Sun",
    title: "It's the Great Pumpkin, Charlie Brown + Over the Garden Wall",
    year: "1966 / 2014",
    runtime: 135,
    status: "Rewatch",
    themeKey: "week4",
    themeTitle: "Week 4: Haunted Ground & Occult Dread",
    notes: "Official Pumpkin Carving Night: double-feature ritual with autumn leaves and harvest spirit",
    synopsis: "The ultimate autumn double feature: Linus vigilantly awaits the arrival of the Great Pumpkin in a frosty autumn field, followed by two brothers lost in the poetic, haunting woodland of the Unknown.",
    subgenre: "Autumn Harvest Folklore / Animation Double-Feature",
    genreCategory: "Family & Dark Fantasy",
    scareRating: 1,
    scareLabel: "Cozy Spooks",
    scareVibe: "Autumn leaves, jazz piano, singing pumpkins, mild woodland folklore",
    director: "Bill Melendez / Patrick McHale",
    backupAlternate: "Coraline (2009) or The Nightmare Before Christmas (1993)",
    icon: "🍂",
    accentColor: "#f97316"
  },
  {
    id: 26,
    dayNumber: 26,
    date: "Oct 26",
    dayOfWeek: "Mon",
    title: "Train to Busan",
    year: "2016",
    runtime: 118,
    status: "Rewatch",
    themeKey: "week4",
    themeTitle: "Week 4: Haunted Ground & Occult Dread",
    notes: "Kinetic, high-velocity zombie survival thriller",
    synopsis: "As a sudden, hyper-aggressive viral outbreak tears across South Korea, a father and his estranged young daughter fight for their lives trapped aboard a speeding high-speed bullet train bound for Busan.",
    subgenre: "High-Octane Zombie Thriller",
    genreCategory: "Zombie & Outbreak",
    scareRating: 4,
    scareLabel: "High Terror",
    scareVibe: "Kinetic sprint zombies, claustrophobic train cars, emotional heartbreak",
    director: "Yeon Sang-ho",
    backupAlternate: "#Alive (2020) or 28 Days Later (2002)",
    icon: "🚆",
    accentColor: "#ef4444"
  },
  {
    id: 27,
    dayNumber: 27,
    date: "Oct 27",
    dayOfWeek: "Tue",
    title: "Colony",
    year: "2026",
    runtime: 100,
    status: "First Watch",
    themeKey: "week4",
    themeTitle: "Week 4: Haunted Ground & Occult Dread",
    notes: "Tense quarantine outbreak siege keeping adrenaline high",
    synopsis: "Trapped deep within an underground quarantine bunker, a fractured crew of survivors must confront both internal paranoia and a hyper-mutating contaminant that breaches their final security perimeter.",
    subgenre: "Outbreak / Quarantine Siege",
    genreCategory: "Zombie & Outbreak",
    scareRating: 4,
    scareLabel: "High Terror",
    scareVibe: "Biohazard alarms, infected shadows, claustrophobic corridor panic",
    director: "Indie Feature",
    backupAlternate: "The Crazies (2010) or [REC] (2007)",
    icon: "☣️",
    accentColor: "#e11d48"
  },
  {
    id: 28,
    dayNumber: 28,
    date: "Oct 28",
    dayOfWeek: "Wed",
    title: "Hocus Pocus",
    year: "1993",
    runtime: 96,
    status: "Rewatch",
    themeKey: "finale",
    themeTitle: "The Finale: All Hallows' Eve",
    notes: "Nostalgic Salem comfort food & witchy celebration leading into Halloween weekend",
    synopsis: "Three resurrected 17th-century Salem witches return to life after a skeptical teenager lights the mythical Black Flame Candle, forcing him, his sister, and a talking cat to stop them before sunrise.",
    subgenre: "Salem Witchcraft / Family Fantasy",
    genreCategory: "Family & Dark Fantasy",
    scareRating: 1,
    scareLabel: "Cozy Spooks",
    scareVibe: "Pure Halloween town nostalgia, Salem autumn, musical spellbinding",
    director: "Kenny Ortega",
    backupAlternate: "The Witches (1990) or Practical Magic (1998)",
    icon: "🧙‍♀️",
    accentColor: "#a855f7"
  },
  {
    id: 29,
    dayNumber: 29,
    date: "Oct 29",
    dayOfWeek: "Thu",
    title: "Exhuma",
    year: "2024",
    runtime: 134,
    status: "First Watch",
    themeKey: "finale",
    themeTitle: "The Finale: All Hallows' Eve",
    notes: "Ancestral curses, shamanic rituals, and unearthed graves",
    synopsis: "Two rising shamans, a veteran feng shui master, and a mortician are hired by a wealthy family to exhume an ancestral grave, only to awaken a terrifying historical curse buried within the soil.",
    subgenre: "K-Occult / Shamanic Mystery",
    genreCategory: "Occult & Folk",
    scareRating: 4,
    scareLabel: "High Terror",
    scareVibe: "Grisly burial customs, ancestral vengeance, bone-chilling shaman rituals",
    director: "Jang Jae-hyun",
    backupAlternate: "The Priest (2015) or Svaha: The Sixth Finger (2019)",
    icon: "⚰️",
    accentColor: "#78716c"
  },
  {
    id: 30,
    dayNumber: 30,
    date: "Oct 30",
    dayOfWeek: "Fri",
    title: "Trick 'r Treat",
    year: "2007",
    runtime: 82,
    status: "First Watch",
    themeKey: "finale",
    themeTitle: "The Finale: All Hallows' Eve",
    notes: "Devil's Night: Anthology honoring Halloween lore, traditions, and Sam",
    synopsis: "Four interwoven tales of horror unfold on Halloween night in an Ohio town, all connected by Sam—a mysterious burlap-masked trick-or-treater who punishes anyone breaking the holiday's sacred rules.",
    subgenre: "Halloween Anthology / Dark Comedy",
    genreCategory: "Slasher",
    scareRating: 4,
    scareLabel: "High Terror",
    scareVibe: "Jack-o'-lantern lore, poisoned candy, quarry ghosts, Halloween spirit",
    director: "Michael Dougherty",
    backupAlternate: "Tales of Halloween (2015) or Creepshow (1982)",
    icon: "🍭",
    accentColor: "#f97316"
  },
  {
    id: 31,
    dayNumber: 31,
    date: "Oct 31",
    dayOfWeek: "Sat",
    title: "Halloween",
    year: "1978",
    runtime: 91,
    status: "Rewatch",
    themeKey: "finale",
    themeTitle: "The Finale: All Hallows' Eve",
    notes: "All Hallows' Eve: The undisputed holiday classic, synth score, and the Shape stalking Haddonfield",
    synopsis: "Fifteen years after brutally slaying his sister on Halloween, the masked killer Michael Myers escapes a psychiatric facility and returns to his Illinois hometown to stalk teenage babysitter Laurie Strode.",
    subgenre: "Foundational Slasher / Masterpiece",
    genreCategory: "Slasher",
    scareRating: 4,
    scareLabel: "High Terror",
    scareVibe: "Relentless synth score, the Shape watching from behind hedges, autumn perfection",
    director: "John Carpenter",
    backupAlternate: "Halloween II (1981) or Halloween (2018)",
    icon: "🎃",
    accentColor: "#ea580c"
  }
];

const THEMES = [
  {
    key: "all",
    label: "All 31 Days",
    dateRange: "Oct 1 – Oct 31",
    icon: "🦇"
  },
  {
    key: "week1",
    label: "Week 1: Cozy Autumn & Folklore",
    dateRange: "Oct 1 – Oct 7",
    description: "Mist-drenched kickoff, cozy stop-motion, harvest veggies & creature fun",
    color: "#f97316",
    icon: "🍁"
  },
  {
    key: "week2",
    label: "Week 2: Practical Blood, 80s Camp & Claws",
    dateRange: "Oct 8 – Oct 14",
    description: "Gory practical transformations, Lovecraftian splatter & southern dread",
    color: "#ef4444",
    icon: "🩸"
  },
  {
    key: "week3",
    label: "Week 3: Psychological Paranoia & Suspense",
    dateRange: "Oct 15 – Oct 21",
    description: "Slow-burn urban dread, siege tension, meta-slashers & suburban angst",
    color: "#8b5cf6",
    icon: "👁️"
  },
  {
    key: "week4",
    label: "Week 4: Haunted Ground & Occult Dread",
    dateRange: "Oct 22 – Oct 27",
    description: "Suburban hauntings, demonology, Korean folk terror & pumpkin ritual",
    color: "#06b6d4",
    icon: "🕯️"
  },
  {
    key: "finale",
    label: "The Finale: All Hallows' Eve",
    dateRange: "Oct 28 – Oct 31",
    description: "Salem comfort, ancestral curses, Sam's rules & Carpenter's Shape",
    color: "#fb923c",
    icon: "🎃"
  }
];

const GENRES = [
  { key: "all", label: "All Genres" },
  { key: "Slasher", label: "🔪 Slasher" },
  { key: "Creature", label: "🐺 Creature Feature" },
  { key: "Ghost & Haunted", label: "👻 Ghost & Haunted House" },
  { key: "Occult & Folk", label: "🕯️ Occult & Folk Horror" },
  { key: "Zombie & Outbreak", label: "🧟 Zombie & Outbreak" },
  { key: "Psychological", label: "🧠 Psychological Suspense" },
  { key: "Family & Dark Fantasy", label: "🎃 Family & Dark Fantasy" }
];
